name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable
          yarn set version 3.6.1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable
          yarn set version 3.6.1
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Configure Git and Push to Another Repo (SSH)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git remote add target-repo git@github.com:wp-optimize/wp-optimize.github.io.git
          yarn install --frozen-lockfile
          yarn build
          git push --force target-repo main