name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable
          yarn set version 3.6.1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable
          yarn set version 3.6.1
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Clone target repository
        run: git clone git@github.com:wp-optimize/wp-optimize.github.io.git
      - name: Clean target repository
        run: |
          cd wp-optimize.github.io
          git rm -rf .
          git clean -fxd
      - name: Copy build artifacts
        run: cp -a build/. wp-optimize.github.io/
      - name: Commit and push changes
        run: |
          cd wp-optimize.github.io
          git config user.email "actions@github.com"
          git config user.name "gh-actions"
          git add .
          git commit -m "Deploy site $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main